### PR TITLE
138 refresh total score

### PR DESCRIPTION
**Pull request by Mushroom-MSL1L**
#138 
1. **_delete_** api /competition/refresh/groups/players/playertotalscore/{id} [patch]
- This is old implementation of refresh player qualification total score.

2. **_create_** api /player/refresh/totalscores/{competitionid} [patch]
- This is new implementation of refresh player qualification total score.

3. refactor api /player/roundscore/{roundscoreid} [patch]
- For the frontend, this api is nothing changed, but the implementation of refreshing total score is the new one.

### CODE REVIEW

**Comment by Mushroom-MSL1L** [comment]
@Otmeal squash and merge ?

**Comment by Otmeal** [comment]
等等，所以還是要戳API分數才會更新嗎？

**Comment by Mushroom-MSL1L** [comment]
> 等等，所以還是要戳API分數才會更新嗎？
> 
> 

#138 Already said, no more additional info you need to know.

**Review by Otmeal — APPROVED** [review]
我原本擔心的是那個有變的api，前端可能會壞。但是我想起來現在前端還是workaround，所以還沒有用到那個API。

**Pull request merged**
