### PR TITLE
Scoring_system_players

### PR DESCRIPTION
**Pull request by Mushroom-MSL1L**
1. request for "scoring_system_players" merge into "feat-merge"
2. basic user and participant functions for completing logics of player (might conflict with profile)
3. unassigned lane function, a special case of lanes 
4. all function about players
5. format uint and int types 
6. merge "feat-merge" to solve conflict

next : elimination

### CODE REVIEW

**Comment by Mushroom-MSL1L** [comment]
Merging conflicts have been solved by merge "Master branch" into "Develop branch".

**Comment by Mushroom-MSL1L** [comment]
又變灰色了？？？？

**Comment by lolainta** [comment]
Sorry, 你先 merge 回你那邊的 branch 不要回 feat-merge 吧，因為 feat-merge 還沒好

**Comment by Mushroom-MSL1L** [comment]
所以是回到merge前的樣子（沒有feat-merge）
然後在把”scoring_system_player“ merge into “scoring_system”嗎？

**Comment by lolainta** [comment]
對 你可以改 head 然後再 force push 就好

**Pull request merged**
